imports:
    - { resource: config.yml }

parameters:
    defer_all_emails: "studymarketing@mailinator.com"
    stripe_api_key: "sk_test_e6FayAX25zDIq2O17blocj2h"
    stripe_public_key: "pk_test_th5VY2bxRUDSJZ1xCcpJ7CNB"
    database_host: "studysaucedb"

doctrine:
    dbal:
        server_version:       5.6
        driver:   "pdo_sqlite"
        host:     "%database_host%"
        dbname:   "studysauce3"
        user:     "study2"
        password: "itekIO^#(1234"

services:
    cache.app:
        class: Symfony\Component\Cache\Adapter\NullAdapter
    cache.system:
        class: Symfony\Component\Cache\Adapter\NullAdapter
    session.handler.pdo:
            class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
            arguments:
                - "sqlite:///%kernel.root_dir%/session.sqlite"
                - {db_username: "study2", db_password: "itekIO^#(1234", db_table: session, db_id_col: session_id, db_data_col: session_value, db_time_col: session_time, db_lifetime_col: session_lifetime}

monolog:
    handlers:
        main:
            type:         stream
            action_level: debug
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console

